
// user
export const FETCH_ACCOUNT_USER_REQUEST = 'FETCH_ACCOUNT_USER_REQUEST';
export const FETCH_ACCOUNT_USER_FAILURE = 'FETCH_ACCOUNT_USER_FAILURE';
export const FETCH_ACCOUNT_USER_SUCCESS = 'FETCH_ACCOUNT_USER_SUCCESS';

// biz
export const FETCH_ACCOUNT_BIZ_REQUEST = 'FETCH_ACCOUNT_BIZ_REQUEST';
export const FETCH_ACCOUNT_BIZ_FAILURE = 'FETCH_ACCOUNT_BIZ_FAILURE';
export const FETCH_ACCOUNT_BIZ_SUCCESS = 'FETCH_ACCOUNT_BIZ_SUCCESS';
